---
- name: Restart Apache
  service:
    name: "{{ apache_package }}"
    state: restarted
    enabled: yes

- name: Restart MySQL
  service:
    name: "{{ mysql_package }}"
    state: restarted
    enabled: yes
